name: conda_env_SGPocket_gpu
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
- python=3.10
- pip=23.3.1
- numpy=1.24.3
- scipy=1.7.3
- cudatoolkit=11.8
- pytorch=2.1.0=py3.10_cuda11.8_cudnn8.7.0_0
- torchaudio=2.1.0=py310_cu118
- torchvision=0.16.0=py310_cu118
- scikit-learn-intelex=2023.1.1
- pandas=2.1.1
- biopandas=0.4.1
- pyg=2.4.0=py310_torch_2.1.0_cu118
- pytorch-lightning=2.1.0
- xorg-libxrender=0.9.10
- pip:
  - class-resolver==0.3.10
  - tensorboard==2.15.1
  - biopython==1.81